### ISSUE TITLE
Feature request: Auto enrol upon course or activity completion

### ISSUE THREAD

**Issue by Jarvil** [bobopinna/moodle-enrol_autoenrol#1]
Hello,

I would like to see an feature that enrols users to a course X when they receive course or activity completion from course Y.

Maybe you should also condider developing a single autonerol plugin together with this guy; 

https://moodle.org/plugins/enrol_auto

**Comment by Brada65** [comment]
That would be great!

**Comment by jeremy-schweitzer** [comment]
There is a plugin that does the enrol upon completion of another course right now: https://moodle.org/plugins/enrol_coursecompleted

I'm not sure there is a lot of benefit in combining - it's nice to have both. [Side note] Thanks for picking up this plugin and carrying on with the development!

**Comment by bobopinna** [comment]
I agree with Jeremy.
