### ISSUE TITLE
unenrol self does not seem to work

### ISSUE THREAD

**Issue by stemiwe** [bobopinna/moodle-enrol_autoenrol#12]
using AutoEnrol 2.1 2018101902 on Moodle 3.6.3 (Build: 20190311)

even though i granted my students and teachers the permission enrol/autoenrol:unenrolself, they still cannot unenrol themselves from a course that they have been added to with auto enrol

am i missing something, or is this a bug?

**Comment by bobopinna** [comment]
You must set to Yes "Enable self unenrol" setting in autoenrol instance.

**Comment by stemiwe** [comment]
oh, silly me, nevermind then
