### ISSUE TITLE
AutoEnrol creates a new group with the same name even when user is already enrolled in manually created group with that name

### ISSUE THREAD

**Issue by senaiboy** [bobopinna/moodle-enrol_autoenrol#15]
Steps to reproduce:
1. Manually create a group called "Test" in course and add user to it.
2. AutoEnrol set to group user by field. User has the value "Test" in the field.
3. When user logs in, he is automatically enrolled into a new group called "Test". Now we have 2 groups called "Test".

If this was the intended behaviour, is there a way to group them based on group name and not id? Reason being that sometimes groups were created manually (eg using CSV file import) and AutoEnrol now duplicates the group.

**Comment by bobopinna** [comment]
Autoenrol check existence a group using Group ID number so if you manually add a group before autoenrol create it you need to define also the right Group ID number.

Here you find the Group ID number definition:
https://github.com/bobopinna/moodle-enrol_autoenrol/blob/16de8fd44dd8b137b86e8add2705e6f8a453806e/lib.php#L753

**Comment by senaiboy** [comment]
Do you mean we need to input a Group ID number for all manually created groups?

Issue is that with 100s of groups per course, it's a bit cumbersome. We used "Upload Users" to enrol multiple users into multiple courses along with their groups, which didn't allow us to set Group ID in the CSV.

**Comment by bobopinna** [comment]
Fixed. 
Now existing groups also without Group ID but with the right name are populated.
Those groups will not removed on autoenrol instance deletion.
