### ISSUE TITLE
Neither unenrol method works

### ISSUE THREAD

**Issue by jarvil1** [bobopinna/moodle-enrol_autoenrol#19]
Hello,

Neither unenrol method does not work for a student, steps to repeat;

1. Create course with autoenrol

- Enrol When: Loading the course
- Enable self unenrol: YES

2. Open the course as a student and notice that you cannot unenrol.

-----
1. Create course with autoenrol

- Enrol When: Loggin into site

2. Check that student role has enrol/autoenrol:unenrolself allowed

3. Log in to the Moodle and open the course
4. Notice that you cannot unenrol from the course.

Tested with Moodle 3.5 & enrol_autoenrol2.1.1 (2019111800)

**Comment by bobopinna** [comment]
Those are the aspected behaviours.

Students can unenrol only when:
- enrol/autoenrol:unenrolself capability is allowed
- Enrol When: Loading the course
- Enable self unenrol: YES

If we permit to unenrol a student when "Enrol When: Loggin into site" is set on the next site login he/she will be reenrolled.

**Comment by jarvil1** [comment]
Hello,

Thanks for the clarification, I thought there were two ways to unenrol your self from course.
