### ISSUE TITLE
Custom profile field in Group by

### ISSUE THREAD

**Issue by Brada65** [bobopinna/moodle-enrol_autoenrol#2]
Hello Roberto,
I am just testing your version of plugin on my local instance of moodle 3.3.2, and I noticed that you don't have Custom profile field in "Group by" in auto group. It is still just Authentication Method, Department, Institution.... There are no custom field in that dropdown box.

**Comment by bobopinna** [comment]
Hello,
custom profile fields are listed after standard field as shown in this screenshot:
![autoenrol-customfields](https://user-images.githubusercontent.com/8382062/35979683-4097f64c-0ce9-11e8-9634-95c7dfc7f7f4.jpg)
Did you use the last release?

**Comment by bobopinna** [comment]
No more response. Probably solved.

Close issue
