### ISSUE TITLE
Unexpected group naming when using soft match

### ISSUE THREAD

**Issue by nomisge** [bobopinna/moodle-enrol_autoenrol#20]
I want to use the plugin to enrol students and group them depending on their class. The class is specified by a user-profile-field. But I only want to allow certain classes, and not accept all values that might be in that profile-field. I use the plugins "User Filtering", by filtering by that user-profile-field. My classes for one grade are e.g. "5a, 5b, 5c, ..".

Matching by group, without "Allow Only" option works as expected:
 For each possible value in the profile-field a separate group is created. A student from class "5a" gets a group "5a", a student from class "5b" gets a group "5b"

Matching just one possible value works as expected:  
 With the "Allow Only" Setting, I am matching for the allowed value. A group is automatically generated named with the restriction I entered.

Matching several classes does not work as expected: 
 I want to match all classes that start with 5. For that I put "5" in "Allow Only" setting and enable "Soft Match". 
- Expected behavior: A student of class "5a", gets enroled into group "5a", a student from class "5b" in group "5b".
- Observed behavior: Both students of class "5a" and "5b" get enrolled in a group "5".
- Workaround: Create a separate instance of the plugin for each class

I suspect, that if the setting "Allow Only" is not set, the value of the profile field is used as group name. With setting "Allow Only" set, now that value is used as group name. The naming seems to be inconsistent.

I suggest changing the plugin, such that the value of the field is always used as group name. Alternatively an option to toggle between the two behaviors could be implemented.

If you give me a hint where to look at in the code, I am happy to help 'fixing' the issue.
Thanks.

**Comment by bobopinna** [comment]
Your idea could be correct in your context but I think that could be cases where creating one group for each matched field value create a lot of unwanted groups.
Unfortunately it's not so easy to find a solution that match all use cases.

If you want to modify the plugin to match your needs, you can comment lines 691-693 and line 706 of lib.php.

I'll find another way to add more flexibility to autoenrol filtering and groups.

**Comment by bobopinna** [comment]
It could be solved with the new filter system

**Comment by bobopinna** [comment]
Now available on github master branch
