### ISSUE TITLE
Run enrollment as a scheduled task

### ISSUE THREAD

**Issue by rmeske** [bobopinna/moodle-enrol_autoenrol#22]
Since the enrollments on log in do not happen until the users list of courses is created for the Dashboard, it would be great to have the option to run the autoenrol on a schedule.  For larger sites, it may need to perform this in batches.

**Comment by bobopinna** [comment]
Hello,
a couple of week ago I would find a fix for dashboard problem and I committed a scheduled task and a cli command for batches

Please let me know any comment about them
