### ISSUE TITLE
Feature Request: Autoenrol based on role / capability

### ISSUE THREAD

**Issue by amenk** [bobopinna/moodle-enrol_autoenrol#23]
We want - for example - all users which are globally assignd to the teacher role to be able to enroll themselves to any course.

For this reason we think about adding a capability such as `enrol/autoenrol:selfenrol` or a section in the filters so that we can easily select the users which should be able to do this.

If you agree this is a good idea to include into this plugin, we would make a pull request.

What do you think?

**Comment by amenk** [comment]
On a second look, the [similarly named plugin](https://github.com/catalyst/moodle-enrol_auto/blob/561a96f2d1cccb816277e203d8dd802a7e027f3e/db/access.php#L51) might come in handy there, we will try.

**Comment by bobopinna** [comment]
I fully don't understand your context but I think you can do it without any additional plugin.
Just configure capabilities for a specific role.
Note that the teacher role assigned globally or at category level will enroll that user as teacher in all courses.
Probably you need an other way to reach you goal.

**Comment by amenk** [comment]
Thanks for your response :-)

While I did not get this to work without a plugin (we created a new role, with ARCHETYPE = Teacher, assigned the new role globally, still they were not enrolled to each course), the above plugin seems to do just that job.
