### ISSUE TITLE
Remove learners from course, using bulk checkbox options?

### ISSUE THREAD

**Issue by goose2000** [bobopinna/moodle-enrol_autoenrol#24]
Hi - is there a way learners enrolled with autoenroll, could be removed using the multi-select options on the Participants page? Or would this mean a change to Moodle core? I see Manual enrollments have this feature.

Thank you for this work/plugin.
![9c0e61ab-3472-4872-a70d-5fbd7b2a9aef](https://user-images.githubusercontent.com/2395298/118665669-7afdf680-b7c0-11eb-8546-c092de2c5572.png)

**Comment by bobopinna** [comment]
Hi,
it already works from release 2.1.
You can get some problems when use multiple instances of autoenrol in the same course.
At this time the drop down menu display 2 or more Auto Enrol selections but only the first one in enrolment methods works.
You can see the full description in Moodle tracker: https://tracker.moodle.org/browse/MDL-66652

HTH
