### ISSUE TITLE
 Send course welcome message select: from the no-reply adress gives" gives error | Plugin version 2.3.1 | 2021061000

### ISSUE THREAD

**Issue by gemguardian** [bobopinna/moodle-enrol_autoenrol#26]
- Moodle 3.9
- Plugin version 2.3.1 | 2021061000
- PHP 7.2

Could reproduce on Moodle 3.11 php 7.3 .
--------------------------------------
**steps**

1. Add enrollement methode to course
2. Select at "Send course welcome message": From the no-reply address"
3. Save enrollement

You will see the error "Data submitted is invalid"

![image](https://user-images.githubusercontent.com/16559999/121901706-eaff8e00-cd26-11eb-9ba3-38cea807be22.png)

**Comment by bobopinna** [comment]
Sorry there was a bad data validation. 
Now fixed.

Thanks a lot

**Comment by gemguardian** [comment]
No worries :) thank you for your super fast fix.
I have tested it, and it works now as it should.
