### ISSUE TITLE
Does not enrol via e-mail match

### ISSUE THREAD

**Issue by relecand** [bobopinna/moodle-enrol_autoenrol#3]
First of all: thank you for this great plugin.

My environment:
- Moodle 3.4
- PHP 7.2
- Autoenrol 2.0 (lastest commit: 3645d96)

Steps to reproduce:
1. Add autorenrol to a course
2. Enrol when: Logging into site
3. Group by: e-mail address
4. Allow only: domain.com (also tried with just "domain") - or any other domain

Users with email adresses that contains @domain.com (or any other domain) will not be enrolled into the course. There are no debug messages.

Would be great if you look into this issues! Thank you very much!

**Comment by bobopinna** [comment]
Fixed in last commit. It was a typo in lib.php.
Please, be sure to set softmatch to yes in order to match domain name in email addresses.

**Comment by relecand** [comment]
Thank you!
