### ISSUE TITLE
Enrolments based on AutoGroup groupings

### ISSUE THREAD

**Issue by sgodbehere01** [bobopinna/moodle-enrol_autoenrol#33]
Hi there, 

We currently have a situation where we would like users to be enrolled onto a course on the condition that the group they would be placed onto belongs to a particular grouping, based on the grouping filter. We are using AutoGroups and the group the user is placed into is based on a custom field in their profile. I've attached some screen-shots to help try to illustrate what we are trying to achieve. 

![Screenshot from 2021-11-23 16-46-47](https://user-images.githubusercontent.com/31889885/143067462-da6031fc-bb66-4c2c-9049-63c7dad80f17.png)
![Screenshot from 2021-11-23 16-46-30](https://user-images.githubusercontent.com/31889885/143067468-6d9f652d-1255-4ca5-9d51-a37f1defdeaf.png)
![Screenshot from 2021-11-23 16-53-13](https://user-images.githubusercontent.com/31889885/143068581-657f547b-0117-4251-9321-8d0a0c8907a5.png)

Currently this doesn't seem possible, as with these filters any user visiting the page isn't being enrolled, which I assume is because technically when they load the course they are not yet in a grouping, because they are not in a group. Is it possible for the group/grouping check to be made as they are enrolled? Would this perhaps require us to use the "Group By" option in the user filtering, rather than making the groups manually? 

Let me know if this is a possibility, if it should be possible as is or if you'd like any more information or clarification. 

Kind regards,

Sam

**Comment by bobopinna** [comment]
Hi Sam,
for what I could understand, you can't filter on groupings.
Generally you can't filter users using something defined or assigned in the course. 
You need to use something that is defined and visible outsite the course like a profile field, a badge, course completion.

I can suggest you to filter users by the custom field that is used to create groups. If you use the Group by option you don't need Auto Group, groups will be created by Autoenrol.
