### ISSUE TITLE
End date (Expiration date) not working for me

### ISSUE THREAD

**Issue by tumaltas** [bobopinna/moodle-enrol_autoenrol#34]
Hello Roberto. I am having issues with Autoenrol plugin for moodle. It is a great plugin and does a lot of work; however, when I disable Enrolment duration and enable "End date", the expiration function does not appear on user in the participants area; it gives unlimited access. Epiration works when I enable "Enrolment duration" though; but I need to set an end date and it is not working. Is there a bug or am I missing something? I need your help.
Thank you
Tumer

**Comment by bobopinna** [comment]
Hello Tumer,
end date, as for other enrolment plugins, just blocks new enrolments after that date but keep active old enrolments until expiration.
If you want to block access to course after a date I think you can add a date restriction rule in user filter setting it until your "End date". Date restrinction needs to be enabled in Autoenrol plugin administration settings.
You need to check administration setting "Auto unenrol action" in order to do the right thing when the rule does not match anymore (unenrol user, keep enrolled, disable enrolment, etc).

HTH,
Roberto

PS: I'll post the same answer on moodle.org as a FAQ for other moodlers

**Comment by bobopinna** [comment]
This is could be a new feature request.
Add a new field in autoenrol settings where define a enrolment end date as alternative to enrolment duration.

**Comment by tumaltas** [comment]
Thank you Roberto for your kind reply and the time you spared for me today;
I really appreciate that.

For the time being, I guess I will wait for the feature too be added. I
tried the method to add end date in "user filter" but it seems to be for
the purpose of disallowing a user to enroll before that date; not for
enrolling until that date (though that one also didn't work and allowed the
user to enroll). So, I will be looking forward to hearing from you about
the feature added/fixed. It is in fact there and for that purpose but
somehow it doesn't work. It works for manual enrolments and with other
enrolment plugins; so, there might be a missing piece of code, I think.

Best wishes.
Tümer ALTAŞ
Instructor, Ankara University
School of Foreign Languages
Mobile: 0 530 238 0585
E-mail: ***@***.***

**Comment by bobopinna** [comment]
Hello Tumer,
I tried to implement enrolment duration until a specified date.
There are a lot of thinking about it so I decided to branch this sub project before implement in standard autoenrol release.

The first thinking is: what should happen if a teacher define a due date, some students enrol in the course, and then the teacher change the due date. With the current implementation those students still enrolled until the first set due date. Some might prefer that the expiration date be changed for all enrolled users based on the new expiration date, this change could be a very lengthy process, depending on the number of users.

You can download the new branch from:
https://github.com/bobopinna/moodle-enrol_autoenrol/archive/refs/heads/duration_date.zip

**Comment by tumaltas** [comment]
Thank you very much Roberto, I will try.
Best
Tümer ALTAŞ
Instructor, Ankara University
School of Foreign Languages
Mobile: 0 530 238 0585
E-mail: ***@***.***
