### ISSUE TITLE
Including Course URL in Welcome email

### ISSUE THREAD

**Issue by rmeske** [bobopinna/moodle-enrol_autoenrol#35]
Hello,

I am trying to include the URL of the course in the Welcome email.  I thought I saw somewhere this should be $a->link, but it is not working.

I created a Pull request with a fix for your review.

Regards,
Ron

**Comment by bobopinna** [comment]
Hello Ron,
I seen your pull request.
I am torn as I am trying to keep autoenrol behavior as aligned as possible with self-enrollment.

I'll think a bit before merge it.

Cheers,
Roberto

**Comment by rmeske** [comment]
Hello Roberto,

I understand wanting to keep it aligned with existing functionality.  Thank you for considering my request.

I would like to point out the main difference between self-enrollment and auto-enroll.  

With Self-enrollment, the user knows about the course and has selected it to enroll in.  Once they enroll they can immediately launch the course.

With Auto-enroll, the user may not know about the course and had not chosen to enroll in it.  When they receive the email, and there is a link in it, it gives them the ability to immediately launch it, similar to self-enrollment.  This makes it easier on the user and gets better response than relying on the user to sign into Moodle, locate the appropriate course and then click on it.

Happy holidays,
Ron
