### ISSUE TITLE
Error when adding the enrollment method to a new course 

### ISSUE THREAD

**Issue by pandlewill** [bobopinna/moodle-enrol_autoenrol#38]
Debug info: Incorrect integer value: '-' for column 'customchar3' at row 1
INSERT INTO mdl_enrol (enrol,status,courseid,enrolstartdate,enrolenddate,timemodified,timecreated,sortorder,customint1,customint3,customint4,customint5,customint6,customint7,customint8,customchar1,customchar3,customtext1,customtext2,name,roleid,enrolperiod,expirynotify,expirythreshold,notifyall) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
[array (
0 => 'autoenrol',
1 => '0',
2 => '1435',
3 => 0,
4 => 0,
5 => 1644260373,
6 => 1644260373,
7 => '3',
8 => '1',
9 => '0',
10 => '1',
11 => 0,
12 => 0,
13 => '0',
14 => '0',
15 => 0,
16 => '-',
17 => 0,
18 => '{"op":"&","c":[],"showc":[]}',
19 => 'test',
20 => '5',
21 => 0,
22 => '0',
23 => 0,
24 => 0,
)]
Error code: dmlwriteexception
Stack trace:

    line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
    line 1357 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
    line 1403 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
    line 2469 of /lib/enrollib.php: call to mysqli_native_moodle_database->insert_record()
    line 155 of /enrol/autoenrol/edit.php: call to enrol_plugin->add_instance()

**Comment by bobopinna** [comment]
Hello,
this is a strange error, customchar3 field is not an integer field and the '-' value is a correct value.
Could you check your database definition for table mdl_enrol?
customchar3 must be defined as char (1333) field.
Which Moodle release did you use?

**Comment by pandlewill** [comment]
Hi 

I use 3.9.2

**Comment by bobopinna** [comment]
Please check your database definition for table mdl_enrol.
customchar3 must be defined as char (1333) field.
If not you need to fix it.

**Comment by pandlewill** [comment]
this is my table structure
`id` bigint(10) NOT NULL,
  `enrol` varchar(20) NOT NULL DEFAULT '',
  `status` bigint(10) NOT NULL DEFAULT '0',
  `courseid` bigint(10) NOT NULL,
  `sortorder` bigint(10) NOT NULL DEFAULT '0',
  `name` varchar(255) DEFAULT NULL,
  `enrolperiod` bigint(10) DEFAULT '0',
  `enrolstartdate` bigint(10) DEFAULT '0',
  `enrolenddate` bigint(10) DEFAULT '0',
  `expirynotify` tinyint(1) DEFAULT '0',
  `expirythreshold` bigint(10) DEFAULT '0',
  `notifyall` tinyint(1) DEFAULT '0',
  `password` varchar(50) DEFAULT NULL,
  `cost` varchar(20) DEFAULT NULL,
  `currency` varchar(3) DEFAULT NULL,
  `roleid` bigint(10) DEFAULT '0',
  `customint1` bigint(10) DEFAULT NULL,
  `customint2` bigint(10) DEFAULT NULL,
  `customint3` bigint(10) DEFAULT NULL,
  `customint4` bigint(10) DEFAULT NULL,
  `customint5` bigint(10) DEFAULT NULL,
  `customint6` bigint(10) DEFAULT NULL,
  `customint7` bigint(10) DEFAULT NULL,
  `customint8` bigint(10) DEFAULT NULL,
  `customchar1` varchar(255) DEFAULT NULL,
  `customchar2` varchar(255) DEFAULT NULL,
  `customchar3` varchar(1333) DEFAULT NULL,
  `customdec1` decimal(12,7) DEFAULT NULL,
  `customdec2` decimal(12,7) DEFAULT NULL,
  `customtext1` longtext,
  `customtext2` longtext,
  `customtext3` longtext,
  `customtext4` longtext,
  `timecreated` bigint(10) NOT NULL DEFAULT '0',
  `timemodified` bigint(10) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Instances of enrolment plugins used in courses, fields marke';

**Comment by bobopinna** [comment]
Everything seems to be fine with autoenrol and your database.
That field has been set up this way since the initial autoenrol release a few years ago.
I tested it on Moodle 3.9.12 with no errors.

My final tip is: try updating your Moodle installation.

HTH,
Roberto

**Comment by pandlewill** [comment]
okay will do so , Thanks
