### ISSUE TITLE
"Notify before enrolment expires" reverts settings to teacher only

### ISSUE THREAD

**Issue by SYoung3000** [bobopinna/moodle-enrol_autoenrol#39]
Hi all, simple issue but we're not sure of why or if we can resolve.

 In every case we've found, when amending the "Notify before enrolment expires" setting to "teacher and enrolled user" it will revert back to "teacher only" - There's no real documentation on this and I've not noticed anyone else observing the problem, hopefully you can shed some light on this?

**Comment by bobopinna** [comment]
Hi,
sorry the form miss to reset to right value.
I just fixed it.
Please update to last commit.

Roberto
