### ISSUE TITLE
Autoenrolled course doesn't show up on my moodle -page

### ISSUE THREAD

**Issue by Jarvil** [bobopinna/moodle-enrol_autoenrol#4]
Hello,

Autoenrolled course doesn't show up on my moodle -page instantly when you log in to the moodle. If you have a course A that has autoenrol with "when logging in to site" setting set and then you log in to moodle as a student you don't see the course on your "my moodle" -page until you refresh the page manually. Could you change the plugin so that the courses are displayed immidiatelly after log in?

**Comment by Jarvil** [comment]
@bobopinna @markward

**Comment by bobopinna** [comment]
Sorry,
this does not depends by autoenrol plugin but by Moodle core.
When the plugin is called by Moodle the user status is already loaded so new enrolments need a page reload to be displayed.

**Comment by bobopinna** [comment]
See https://tracker.moodle.org/browse/MDL-34488 for details.
