### ISSUE TITLE
Validation problem

### ISSUE THREAD

**Issue by renerosser** [bobopinna/moodle-enrol_autoenrol#40]
Hi, I saw another post identical to this on the comments on the Moodle listing on 31st May 2022, but didn't see any resolution or suggestions made. The user's comment was for Moodle 4, but we have the plugin installed on a 3.9 site and it is giving the same issue. 

When adding auto-enrolment to a course, the following error shows:
![Screenshot 2022-06-17 at 09 20 12](https://user-images.githubusercontent.com/37530377/174246706-ce217e2d-c08b-4e5e-b1c8-0108fb1fbe6c.png)

We recently updated the plugin to the latest version (2.3.7 Build 2022051100) and the issue has been present since then.

Please advise as to whether this is a configuration issue with the new version or if this is a bug that can be fixed? 
 
Thanks

**Comment by bobopinna** [comment]
Hi,
version 2.3.7 had that bug.
I solved it on 2.3.8, the current master release here on github.
I release it today on moodle.org.

HTH
