### ISSUE TITLE
Does not work with Moodle Mobile App - and has additional undesired effect

### ISSUE THREAD

**Issue by skillsetltd** [bobopinna/moodle-enrol_autoenrol#41]
We find that AutoEnrol does not appear to work for users viewing a course using the Mobile app.  If a user tries to access a course with autoenrol and manual enrolment enabled, but with self enrol disabled (per Screenshot 1), you see Screenshot 2.

Doing what seems the most obvious thing then, which is to enable Self Enrol so that the student can access, allows the student to self enrol on the course, but also seems to then have the side effect of the student getting immediately enrolled in multiple DIFFERENT courses (the prefix_user_enrolment records that get created are all for the autoenrol enrolids for these courses) despite never having viewed these courses before on this user, or having viewed those courses before within the app.

If you have any sizeable number of courses, this can slow anything but the very latest mobile devices down to a crawl as they load all the new courses into the dashboard.  See attached video, shot on a Pixel 3a (not brand new, but not ancient) - when refreshing the dashboard, it takes a very long time to retrieve and render all the courses that the user has suddenly been enrolled on.

So basically we are stuck - if we remove AutoEnrol, then our web based site doesn't work how we want, and if we just add self-enrol to all the courses, then our mobile users end up immediately enrolled on all the courses on the entire site. Neither of these are great solutions.

Any assistance would be most gratefully received!

Moodle: 3.9.13
AutoEnrol: 2.3.6 (this is the only non-core enrolment method installed)
Mobile App: 4.0.1 running on Google Pixel 3a running up-to-date Android 12, but behaviour is the same on other devices e.g. iPhone

**Screenshot 1:**
![Screenshot 1](https://user-images.githubusercontent.com/92787643/179429037-3e3b7e69-46e0-4f99-ba5e-dc276c770656.png)

**Screenshot 2:**
![Screenshot 2](https://user-images.githubusercontent.com/92787643/179429042-c33f59ce-9e16-4044-a800-9787fac84170.png)

**Video:**
![Video](https://user-images.githubusercontent.com/92787643/179429281-16e3c63f-e799-47ce-afdf-911fcfe18ccb.mp4)

**Comment by bobopinna** [comment]
Hello,
that bug was fixed in 2.3.7.
Please upgrade to 2.3.9 and let me now.

Best regards,
Roberto
