### ISSUE TITLE
Error when enabeling Autoenrol in course

### ISSUE THREAD

**Issue by ghenzinger** [bobopinna/moodle-enrol_autoenrol#5]
I installed the Plugin (2.0 2018022600) on my local Moodle  3.3.2+ OS: Windows 10 XAMPP Machine

Using autoenrol in a course i got the following errorscreen after saving the settings for autoenrol.

![untitled](https://user-images.githubusercontent.com/37397828/39040752-06ce1fa0-4488-11e8-9852-fddd0f0e2da2.png)

I checked the autoenrolment by entering the course, which seems working. The autoenrol by logging in is not working.

These are the settings i used:
![capture1](https://user-images.githubusercontent.com/37397828/39041475-1e4b348c-4489-11e8-8e4a-0b3372824e79.PNG)
Thank you for your help.
Gerald

**Comment by bobopinna** [comment]
Thanks for bug report.
I fixed it.

Autoenrol on login works but new course enrolments are not shown in dashboard or homepage.
It depends on moodle core, there is no way to fix it in plugin code. See https://tracker.moodle.org/browse/MDL-34488 for details.
