### ISSUE TITLE
Cannot configure the [Enrol When] parameter as it is disable.

### ISSUE THREAD

**Issue by MarcoMag68** [bobopinna/moodle-enrol_autoenrol#52]
Hi, I have installed the AutoEnrol plugin to allow users to access the course after logging in on the moodle site.
However, I cannot get this environment to work properly. I have configured the plugin at site level with the option [enrol_autoenrol | loginenrol] set to Yes. When I add the Auto Enrol mode to the course from the participants menu, I cannot configure the [Enrol When] parameter as it is disabled.

**Comment by bobopinna** [comment]
Hi,
On last release Enron When is always enabled.
I need some information about your installation.
Which plugin version have you installed? Which Moodle version?

**Comment by MarcoMag68** [comment]
[Moodle](http://moodle.org/) [3.7 (Build: 20190520)](http://docs.moodle.org/dev/Releases)
-------
$plugin->version = 2022062000;
$plugin->requires = 2018051700.00;      // Requires this Moodle version (3.5).
$plugin->release = '2.3.9';             // Plugin release.
$plugin->component = 'enrol_autoenrol'; // Full name of the plugin (used for diagnostics).
$plugin->maturity = MATURITY_STABLE;    // The moodle.org release.

**Comment by bobopinna** [comment]
Seems that we already fixed this issue with #48
