### ISSUE TITLE
Auto enrol not working as intended when guest access is enabled on a course

### ISSUE THREAD

**Issue by wtellos** [bobopinna/moodle-enrol_autoenrol#56]
If admin enables the auto enrol method **but also** the guest access method, then instead of auto-enrolling the students, it shows a button "enrol me in this course" so users can manually proceed on enrolling.
If the Guest access method is removed from the course, then the plugin works as intended. 
Using Moodle 4.1.9

**Comment by bobopinna** [comment]
Please see #42
