### ISSUE TITLE
How to automatically add users to a course ? 

### ISSUE THREAD

**Issue by nprime496** [bobopinna/moodle-enrol_autoenrol#58]
> When added to a course this enrolment plugin can enrol users onto a course automatically, either as they log in to your Moodle site or as they access to the course.

Hi, I'd like to know please to how to automatically add my users to a course ? 

I can't find any tutorial on how to use the plugin on your page : https://moodle.org/plugins/enrol_autoenrol

There's a suggestion that it can be done in #48 but I don't know how. I can't find the `Allow enrolments on login` option.

![Screenshot from 2024-05-24 16-06-55](https://github.com/bobopinna/moodle-enrol_autoenrol/assets/54849528/453ee046-4384-4d70-8c5d-788d734729c7)

**Comment by nprime496** [comment]
I managed to do it, it was not straigthforward. The plugin was disabled after installation, I had to enable it.

**Enable the plugin**
Go to Administration site > Plugins > All Plugins

Search for `enrol_autoenrol`

Click on the gear next to it. You'll see a list of enrolment methods, click on the eye next to "Auto Enrol" to activate it.

**Activate Auto Enrol on your course**

Next, go to your course and activate edition mode, next go to participants.

Select `Enrolment methods` in the select field menu.

Add `Auto Enrol` as a method.

Now, new users shall be automatically added to your course.

**Comment by bobopinna** [comment]
Hello,
I'm sorry if you get trouble in AutoEnrol installation and configuration. 
These are standard Moodle enrolment plugin installation infos, all additional enrolment plugins should be enabled.

You could already found Install section in [README.md](https://github.com/bobopinna/moodle-enrol_autoenrol/blob/master/README.md), next you can follow [Moodle documentation about enrolment plugins](https://docs.moodle.org/en/Enrolment_methods#Managing_enrolment_methods).

Please use with care enrol on login in your sites.
Depending on how many AutoEnrol instances configured in this way and how many users login to your site in period of time, you can get performance issues on your sites.

**Comment by nprime496** [comment]
I don't understand how I missed it.

Thank you.
