### ISSUE TITLE
Feature Request: Conditional enrolments according to custom profile fields

### ISSUE THREAD

**Issue by nauticalist** [bobopinna/moodle-enrol_autoenrol#6]
It would be great if we can select multiple conditions in "User Filtering" section.For example:
If customfield1value = A **AND** customfield2value = 2 process enrolment
If customfield1value = A **OR** customfield2value = 2 process enrolment

Thanks

**Comment by bobopinna** [comment]
Hello,
I will check how implement it.

**Comment by gemguardian** [comment]
Hello, 
This might help: https://moodle.org/plugins/enrol_attributes

I am interesting in funding this extension of the plugin. Could you please contact me on gemma@ltnc.nl 

Gemma

**Comment by bobopinna** [comment]
Now available on github's master branch
