### ISSUE TITLE
Feature request: allow users unenrol from the course

### ISSUE THREAD

**Issue by Jarvil** [bobopinna/moodle-enrol_autoenrol#7]
Hello,

If user is enrolled to the course with autoenrolment they cannot unenrol themselves from the course, please allow this

**Comment by bobopinna** [comment]
Hello,
we can add this feature but it could confuse some users.
On courses with autoenrol on course access the user will be enrolled again on next access to that course. This could be ok.
For courses with autoenrol on site login the user will be enrolled again on next login. This could be strange for some users.

**Comment by Jarvil** [comment]
Hello,

Maybe you can add it as an option in autoenrol so you can turn it on/off depending your need? And I mean as an option in the current courses autoenrol-enrolmentmethod.

**Comment by Jarvil** [comment]
Hello,

Any progress on this feature?

**Comment by bobopinna** [comment]
Sorry, I reviewed the code today.
That feature was already implemented but the capability unenrolself was not set to student by default.
You need to manually consent it to student role.

**Comment by bobopinna** [comment]
Added as default capability to student but you may need to reset role to see the change.

**Comment by bobopinna** [comment]
Added setting to manage self unenrol in instance settings.
