### ISSUE TITLE
More unenrol control options

### ISSUE THREAD

**Issue by jeremy-schweitzer** [bobopinna/moodle-enrol_autoenrol#8]
It would be beneficial to control what happens when a user's criteria no longer match or any unenrol action occurs. This is something that is implemented in several other enrollment plugins, but it generally looks something like this:
![2018-05-25 11_24_02-window](https://user-images.githubusercontent.com/10454996/40555580-33f97e64-600f-11e8-80a1-48bc8e5e6f08.png)

It would be nice to have a bit more control over how that gets handled. Thanks!

**Comment by bobopinna** [comment]
I'll work on it.

**Comment by bobopinna** [comment]
Implemented.
