### ISSUE TITLE
User Filter Value Required

### ISSUE THREAD

**Issue by mlohoar** [bobopinna/moodle-enrol_autoenrol#9]
I got the following after using the AutoErnol on a course.

Notice: Undefined property: stdClass::$customchar3 in xxxxx\enrol\autoenrol\edit.php on line 121

I tracked back the $customchar3 to be the User Filtering Group By field in the settings.  
If you pick a value here the error does not occur.
Should the code be optional or the field be mandatory?

**Comment by bobopinna** [comment]
Hello,
this was already fixed.
I think you are using an old release because line 121 of xxxxx\enrol\autoenrol\edit.php is an empty line on the latest version.
Please try to update to current release from github.
